version: '3'
services:
  app:
    build: .
    ports:
      - "85:85"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: